Title =  ""
LanguageCode = "zh-cn"
BaseUrl = "https://www.zyg-tech.me"
Theme =  "next"
MetaDataFormat =  "yaml"
CanonifyUrls =  true
BuildDrafts =  false
PaginatePath =  "p"
Paginate = 8
DisablePathToLower =  false
HasCJKLanguage = true
PreserveTaxonomyNames = false
UglyUrls = false
PygmentsStyle = "monokai"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
DefaultContentLanguage = "zh-cn"

[Params]
  Introduce = "Programmer & Architect"
  Description = "zyg | 博客 | 软件 |  Java"
  Keywords =  "zyg,独立,博客,程序员,个人,思考,读书,笔记,技术,分享,java"
  Subtitle = "人生天地间，忽如远行客"
  Imglogo = "/img/logo.png"
  #AuthorImg = "/img/author.jpg"
  DateFormat = "2019-01-02"
  YearFormat = "2019年"
  MonthFormat = "01-02"
  Fancybox = true

[Author]
  Name = "zyg"

[Params.Share]
  Baidu = true

[Params.utterances]  
  owner = ""         # Your GitHub ID
  repo = ""          # The repo to store comments

[[Menu.Main]]
  Name = "首页"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "技术"
  Pre = "code"
  URL = "/categories/技术/"
  Weight = 2
[[Menu.Main]]
  Name = "笔记"
  Pre = "book"
  URL = "/categories/笔记/"
  Weight = 4
[[Menu.Main]]
  Name = "杂记"
  Pre = "leaf"
  URL = "/categories/杂记/"
  Weight = 5
[[Menu.Main]]
  Name = "归档"
  Pre = "archive"
  URL = "/post/"
  Weight = 6
[[Menu.Main]]
  Name = "关于"
  Pre = "user"
  URL = "/about/"
  Weight = 7

[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/1162492411/"

[[Params.Socials]]
  Name = "知乎"
  Icon = "globe"
  URL = "https://www.zhihu.com/people/momo0528/" 

[languages.zh-cn]
languageCode = "zh-cn"